"""empty message

Revision ID: 1e7e6e1fc502
Revises: None
Create Date: 2016-10-06 22:08:13.113808

"""

# revision identifiers, used by Alembic.
revision = '1e7e6e1fc502'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['username'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    ### end Alembic commands ###
