"""empty message

Revision ID: 57299b64c104
Revises: None
Create Date: 2016-10-03 16:48:43.490561

"""

# revision identifiers, used by Alembic.
revision = '57299b64c104'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['username'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    ### end Alembic commands ###
