"""empty message

Revision ID: f3479251d229
Revises: 384a8bbae314
Create Date: 2016-10-02 20:45:29.761471

"""

# revision identifiers, used by Alembic.
revision = 'f3479251d229'
down_revision = '384a8bbae314'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['username'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    ### end Alembic commands ###
